# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationForm', '0030_auto_20160906_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAssignment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Faculty_Advisor_Email', models.EmailField(max_length=254)),
                ('Country_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_1_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_2_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_3_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_4_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_5_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_6_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_7_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_8_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_9_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_10_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_11_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_12_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_13_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_14_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_1', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_2', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_3', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_4', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_5', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_6', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_7', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_8', models.CharField(max_length=120, null=True, blank=True)),
                ('Country_15_Committee_9', models.CharField(max_length=120, null=True, blank=True)),
            ],
        ),
    ]
