# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationForm', '0034_auto_20161003_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_10_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_1_Committee',
            field=models.CharField(max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_2_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_3_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_4_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_5_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_6_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_7_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_8_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='delegateinput',
            name='Delegate_9_Committee',
            field=models.CharField(blank=True, max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
        migrations.AlterField(
            model_name='positionpaper',
            name='Your_Committee',
            field=models.CharField(help_text=b'<em><small><small>Please enter the name of your committee</small></small></em>', max_length=120, null=True, choices=[(b'African Union', b'African Union'), (b'United Nations General Assembly', b'United Nations General Assembly'), (b'United Nations Framework on Climate Change: COP 22', b'United Nations Framework on Climate Change: COP 22'), (b'The Commission on the Status of Women', b'The Commission on the Status of Women'), (b'United Nations Economic and Social Commission for Asia and the Pacific', b'United Nations Economic and Social Commission for Asia and the Pacific'), (b'United Nations Educational, Scientific and Cultural Organization', b'United Nations Educational, Scientific and Cultural Organization'), (b'World Health Organization', b'World Health Organization'), (b'8th Congress', b'8th Congress'), (b'Canadian Confederation', b'Canadian Confederation'), (b'International Atomic Energy Agency 2017', b'International Atomic Energy Agency 2017'), (b'Czechoslovakia Government 1990', b'Czechoslovakia Government 1990'), (b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization', b'United Nations Office for Outer Space Affairs and International Civil Aviation Organization'), (b'Venezuelan National Assembly', b'Venezuelan National Assembly'), (b'National Football League 2016', b'National Football League 2016'), (b'Microsoft', b'Microsoft'), (b'Apollo 13', b'Apollo 13'), (b'World War II', b'World War II'), (b'Ad Hoc', b'Ad Hoc'), (b"The Handmaid's Tale", b"The Handmaid's Tale"), (b"Queen Anne's Revenge", b"Queen Anne's Revenge"), (b'Salem Village', b'Salem Village'), (b'Third Servile Revolt', b'Third Servile Revolt'), (b'First Scottish War of Independence', b'First Scottish War of Independence')]),
        ),
    ]
